### ISSUE TITLE
POST /users API inconsistency  

### ISSUE THREAD

**Issue by kujiraOo** [RohanNg/TaskMS#1]
There is inconsistency in API schema for POST /users

```
...
	"lastName" : "Nguyen",
	"contactDetail" : {
		"address" : {
			"street" : "",
			"postalCode": "",
			"city" : ""
		},
		"email" : "some email",
		"phoneNumber": ""
	}
...
```

Should be renamed field _"contactDetail"_ ->  _"contactDetail**s**"_

I also suggest renaming _objectModels.userGroup.ContactDetail_ -> _objectModels.userGroup.ContactDetail**s**_ to avoid confusion in the future

**Comment by RohanNg** [comment]
Thanks, I fixed the consistency
